>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
>>> bg = BaseGeometry()

>>> bg.integer_validator("str", 69)

>>> bg.integer_validator("str", "Santiago")
Traceback (most recent call last):
TypeError: name must be an integer

>>> bg.integer_validator("str", 0)
Traceback (most recent call last):
ValueError: age must be greater than 0

>>> bg.integer_validator("str", -6)
Traceback (most recent call last):
ValueError: distance must be greater than 0

>>> bg.integer_validator("str", [1, 2, 3])
Traceback (most recent call last):
TypeError: suma must be an integer

>>> bg.integer_validator("str")
Traceback (most recent call last):
TypeError: integer_validator() missing 1 required positional argument: 'value'

>>> bg.area()
Traceback (most recent call last):
Exception: area() is not implemented

>>> bg.integer_validator()
Traceback (most recent call last):
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

>>> bg.integer_validator("str", None)
Traceback (most recent call last):
TypeError: suma must be an integer

>>> bg.integer_validator("str", float('inf'))
Traceback (most recent call last):
TypeError: suma must be an integer

>>> bg.integer_validator("str", float('nan'))
Traceback (most recent call last):
TypeError: suma must be an integer

>>> bg.integer_validator("str", 16.6)
Traceback (most recent call last):
TypeError: suma must be an integer

>>> bg.integer_validator("", 10)

>>> bg.integer_validator("str", 1, 2)
Traceback (most recent call last):
TypeError: integer_validator() takes 3 positional arguments but 4 were given

>>> bg.integer_validator("str", kk)
Traceback (most recent call last):
NameError: name 'test' is not defined

>>> bg.integer_validator("str", (1, 2, 3))
Traceback (most recent call last):
TypeError: suma must be an integer

>>> bg.integer_validator("str", {1, 2, 3})
Traceback (most recent call last):
TypeError: suma must be an integer

>>> bg.integer_validator(, 12)
Traceback (most recent call last):
SyntaxError: invalid syntax

>>> bg.integer_validator("suma", True)
Traceback (most recent call last):
TypeError: suma must be an integer
